### ISSUE TITLE
Context Preserving for Statements Missing

### ISSUE THREAD

**Issue by cw00dw0rd** [ArangoDB-Community/ArangoRDF#11]
Currently, on import, a statement is defined as an edge, and its `_from` and `_to` attributes are hashed values. 

```IRI/123 -> Statement/ea84082de (predicate) <- Literal/a4a (Fred)```

This same statement could be generated in the event that the same IRI points towards `Fred`, and as the `_key` values are generated based on at least `_type` and `_value`, the documents will be updated by default and the same goes for the edge statement. 

This is a correct outcome but does not fit 1-1 when attempting to export and isn't aware of the context for the statement. This could be describing a different `Fred` or the same thing could be being said about `Fred` by another person. So, even though it is the same statement, it could have a different context. This is currently not accounted for with our current implementation and should be addressed.

**Comment by aMahanna** [comment]
Addressed in #15 via the `use_hashed_literals_as_keys` parameter

ref: https://arangordf.readthedocs.io/en/latest/specs.html#arango_rdf.main.ArangoRDF.rdf_to_arangodb_by_rpt
