### ISSUE TITLE
Input Directory Support

### ISSUE THREAD

**Issue by cw00dw0rd** [ArangoDB-Community/ArangoRDF#14]
Add support for supplying a directory as an import location. Ideally, this could account for multiple formats either by ignoring files without the specified format or offer a way to supply multiple formats.
```
adb_graph = adb_rdf.import_rdf("./examples/data/", format=["xml", "ttl"], config=config, save_config=True)
```

**Comment by aMahanna** [comment]
Indirectly addressed by #15 

RDF to ArangoDB accepts an `rdflib.graph.Graph` object instead of files, keeps things clean
