### ISSUE TITLE
RDF to Linked Property Graph Translation (Remove `import_ontology` methods)

### ISSUE THREAD

**Issue by cw00dw0rd** [ArangoDB-Community/ArangoRDF#6]
Translate RDF to be more ArangoDB styled graph. 
Possible additions:
- Initialize collections based on OWL/RDFS meta model via parsing supplied file/url
- Collections are created for RDF types (ex: song collection containing song documents)
  - Class collection containing classes (ex: document describing song class type)
- Literals become properties on statement documents

Currently, the `import_ontology` methods attempt to perform these operations, but the method name and current functionality are not functional and require a lot more work.

Implementing this translation method will align with the ArangoDB model better and offer better performance and analytics use cases.

**Comment by aMahanna** [comment]
As discussed, `import_ontology` has been removed in 4f3195b0b1e7acf0fb38a62af88ec00518e67478

**Comment by aMahanna** [comment]
Closing due to no longer relevant after the changes of #15 and #18
